### ISSUE TITLE
When i supply base64 string it works but during update when the string is from the s3 image sets to nil 

### ISSUE THREAD

**Issue by kamalpandey** [y9v/carrierwave-base64#76]

**Comment by kamalpandey** [comment]
I am using rails: 5.1.4
"carrierwave-base64", '~> 2.5.0'
gem "carrierwave", "~> 1.2.1"

**Comment by TenzinDorjee101** [comment]
were you able to fix this ?

**Comment by y9v** [comment]
@kamalpandey this gem only works for base64 encoded string of an image
