### ISSUE TITLE
Save as JPG instead of PNG

### ISSUE THREAD

**Issue by jmuheim** [y9v/carrierwave-base64#78]
I have the following model:

```ruby
class ScreenshotUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :file
  convert :jpg

  version :thumb do
    process resize_to_fill: [50, 50]
  end

  def extension_whitelist
    %w(jpg jpeg gif png)
  end

  version :print do
    process border: ['black']
    process quality: 80
  end
end
```

The upload of the image happens via pasting an image from the clipboard via https://github.com/layerssss/paste.js and is saved as a base64 encoded string into a <textarea>, then uploaded using the https://github.com/y9v/carrierwave-base64 gem:

```ruby
class Finding < ApplicationRecord
  mount_base64_uploader :screenshot, ScreenshotUploader
end
```

In the HTML form, it looks like this:

![image](https://user-images.githubusercontent.com/1814983/76411459-22e48c80-6392-11ea-8280-2b72e13978f8.png)

After uploading, the result is the following files:

- `screenshot.png` it's a PNG, not a JPG!
- `thumb_screenshot.jpg`
- `print_screenshot.jpg`

But I need the original file to be also converted to JPG, as I need to save disk space. Is there any way of doing this? I tried several methods, but none of them seems to work.

You can find more info on the StackOverflow questions:

- [Carrierwave: convert an uploaded PNG to JPG by replacing the original version](https://stackoverflow.com/questions/60622916/carrierwave-convert-an-uploaded-png-to-jpg-by-replacing-the-original-version)
- [Carrierwave and image versions: version URLs generated wrongly if original file and version file do not have same format (PNG vs. JPG)](https://stackoverflow.com/questions/60634564/carrierwave-and-image-versions-version-urls-generated-wrongly-if-original-file)

**Comment by y9v** [comment]
sorry, but I can't help you here. The issue you have is in `carrierwave` gem, not in `carrierwave-base64`, which only decodes the uploaded file string (which is a PNG, and gets saved as a PNG)
