### ISSUE TITLE
mimemagic dependency

### ISSUE THREAD

**Issue by bengalamx** [y9v/carrierwave-base64#88]
As we all now, mimemagic change his license and yank all the previous versions, so it is being removed from every gem in the Rails world.

There's even a workaround fork for carrierwave: https://github.com/carrierwaveuploader/carrierwave/issues/2548

Can we expect carrierwave-base64 to follow the big bro steps?

**Comment by justisb** [comment]
This was merged & released this morning: https://github.com/y9v/carrierwave-base64/pull/87
